// Actions
export const SET_APPLICATION_SEASON = 'SET_APPLICATION_SEASON';
export const UPDATE_APPLICATION_SEASON = 'UPDATE_APPLICATION_SEASON';
export const SUBMITTED_APPLICATION_SEASON = 'SUBMITTED_APPLICATION_SEASON';
export const RESET_SUBMIT = 'RESET_SUBMIT';
