matrix:
  include:
    - language: node_js
      node_js:
        - "lts/*"
        - "10"
      before_install:
        - cd frontend
      cache: 
        npm: true
        directories:
          - frontend/node_modules
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
    - language: python
      script:
        - echo "snek"
