matrix:
  include:
    - language: node_js
      node_js:
        - "lts/*"
        - "10"
      before_install:
        - cd frontend
      cache:
        npm: true
        directories:
          - frontend/node_modules
      install:
        - npm install
        - npm run build:css
      script:
        - npm run lint
        - npm run test
      stage: build
        script:
          - npm run build
    - language: python
      python: 3.7
      dist: xenial
      sudo: true

      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - flake8
        - python -m "pytest"
