version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    env_file: ./backend/.env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile.backend
    entrypoint: python /app/examplebackend.py
    #entrypoint: ping 8.8.8.8 
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
