version: '2.1'
services:
  postgres:
    container_name: postgres 
    restart: always
    image: postgres:10
    env_file: ./backend/.env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432"
      - "5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    restart: always
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile.backend
    entrypoint: bash /app/entrypoint.sh
    depends_on:
        postgres:
          condition: service_healthy
    ports:
      - 5000:5000
  frontend:
    restart: always
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - api
    ports:
      - 8080:80


