FROM python:3.7.2

RUN apt-get update -y
   # apt-get install -y python3 python-pip python-dev
RUN mkdir -p /app

WORKDIR /app
# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

RUN ls /app

RUN pip install -r /app/requirements.txt

#COPY . /app

#ENTRYPOINT [ "python" ]

#CMD ["examplebackend.py"]

