FROM python:3.7.2

RUN apt-get update -y

RUN mkdir /app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

ENV FLASK_APP=/app/main.py

ENTRYPOINT [ "bash entrypoint.sh" ]

