export const NAME = 'Name';
export const EMAIL = 'E-Mail';
export const PHONE = 'Phone';
export const PARTNER = 'Partner';
export const PREFFERED_ROOM = 'Preffered room';
export const SEAT_ROLLOVER = 'Seat Rollover';
export const NEEDS = 'Needs';
export const EDIT = 'Edit';
export const NEW_APPLICATION = 'New Application';
