export const SUCCESSFULL_APPLICATION_UPDATE = 'SUCCESSFULL_APPLICATION_UPDATE';
export const UNSUCCESSFULL_APPLICATION_UPDATE = 'APPLICATION_UPDATE_FAILED';
export const RESET_APPLICATION_STATUS = 'RESET_APPLICATION_STATUS';
export const redirectUrl = '/admin/applications/';
export const MASTER_STATUS = [
  'BACHELOR_STUDENT',
  'WRITING_MASTER',
  'PROJECT_ASSIGNMENT',
  'MASTER_STUDENT',
  'OTHER',
];
