export const SUCCESSFULL_APPLICATION_UPDATE = 'SUCCESSFULL_APPLICATION_UPDATE';
export const UNSUCCESSFULL_APPLICATION_UPDATE = 'APPLICATION_UPDATE_FAILED';
export const RESET_APPLICATION_STATUS = 'RESET_APPLICATION_STATUS';
