export const FETCH_APPLICATION_DIRECTLY = 'FETCH_APPLICATION_DIRECTLY';
export const FETCH_APPLICATION_DIRECTLY_FAILED = 'FETCH_APPLICATION_DIRECTLY_FAILED';
export const RESET_REVIEW_APPLICATION_STATUS_CODE = 'RESET_REVIEW_APPLICATION_STATUS_CODE';
