export const SUCCESSFULLY_FETCHED_STUDENTS = 'SUCCESSFULLY_FETCHED_STUDENTS';
export const SUCCESSFULLY_DELETED_STUDENT = 'SUCCESSFULLY_DELETED_STUDENT';
export const SUCCESSFULLY_DELETED_ALL_STUDENTS = 'SUCCESSFULLY_DELETED_ALL_STUDENTS';
export const FETCHING_STUDENTS = 'FETCHING_STUDENTS';
export const FETCHED_STUDENTS = 'FETCHED_STUDENTS';
