export const SUCCESFULLY_FETCHED_STUDENTS = 'SUCCESFULLY_FETCHED_STUDENTS';
export const SUCCESSFULLY_DELETED_STUDENT = 'SUCCESSFULLY_DELETED_STUDENT';
export const SUCCESSFULLY_DELETED_ALL_STUDENTS = 'SUCCESSFULLY_DELETED_ALL_STUDENTS';
