export const _ROOM_START = 'Room period opens';
export const _ROOM_END = 'Room period ends';
export const _SEASON_START = 'Application season opens';
export const _SEASON_END = 'Application season ends';
export const _CREATE_NEW_SEASON = 'Create new application season';
export const _ROOM_END_TOO_EARLY = 'Room period ends before it starts';
export const _SEASON_END_TOO_EARLY = 'The application season ends before it starts';
export const _NEW_APPLICATION_SEASON = 'New Application Season';
export const _ERROR_MESSAGE = 'Something went wrong';
