"""empty message

Revision ID: 09c4c53d6f50
Revises: b30d0f2e08fe
Create Date: 2019-02-26 19:08:26.477671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c4c53d6f50'
down_revision = 'b30d0f2e08fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seats', ['room_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    # ### end Alembic commands ###
