"""empty message

Revision ID: 1d02715dc588
Revises: 879dd56cf0a9
Create Date: 2019-04-01 13:06:27.999420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d02715dc588'
down_revision = '879dd56cf0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('applicationSeasonId', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('queuePlacement', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'application', 'application_season', ['applicationSeasonId'], ['application_season_id'])
    op.create_unique_constraint(None, 'seats', ['room_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'queuePlacement')
    op.drop_column('application', 'applicationSeasonId')
    # ### end Alembic commands ###
