"""empty message

Revision ID: 1ea54c4e2dcd
Revises: bd0ab22b40bc
Create Date: 2019-02-26 11:25:04.408029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea54c4e2dcd'
down_revision = 'bd0ab22b40bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seats', ['room_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    # ### end Alembic commands ###
