"""empty message

Revision ID: 4fb4678712c2
Revises: 6d1dfb46b307
Create Date: 2019-04-02 11:39:14.564935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb4678712c2'
down_revision = '6d1dfb46b307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'applicationSeasonId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('application', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('application', 'applicationSeasonId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
