"""empty message

Revision ID: 5ee3c0b139bb
Revises: f23193dc3876
Create Date: 2019-01-31 14:09:47.120933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ee3c0b139bb'
down_revision = 'f23193dc3876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_season', sa.Column('applicationperiodend', sa.DateTime(), nullable=False))
    op.add_column('application_season', sa.Column('applicationperiodstart', sa.DateTime(), nullable=True))
    op.drop_column('application_season', 'acceptend')
    op.drop_column('application_season', 'acceptstart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_season', sa.Column('acceptstart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('application_season', sa.Column('acceptend', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('application_season', 'applicationperiodstart')
    op.drop_column('application_season', 'applicationperiodend')
    # ### end Alembic commands ###
