"""empty message

Revision ID: 7f7b863179cb
Revises: ee959c1be9fb
Create Date: 2019-03-04 22:07:34.356237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7b863179cb'
down_revision = 'ee959c1be9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seats', ['room_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    # ### end Alembic commands ###
