"""empty message

Revision ID: 91d6388a4976
Revises: 
Create Date: 2019-03-29 09:02:33.336956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d6388a4976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_season',
    sa.Column('application_season_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=False),
    sa.Column('applicationperiodstart', sa.DateTime(), nullable=True),
    sa.Column('applicationperiodend', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_season_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('sub', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('fullname', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('sub'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('seat_name', sa.String(length=2), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('room_id', 'seat_name')
    )
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('needs', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DECLINED', name='applicationstatus'), nullable=False),
    sa.Column('rank', sa.Enum('WRITING_MASTER', 'PROJECT_ASSIGNMENT', 'MASTER_STUDENT', 'BACHELOR_STUDENT', 'OTHER', name='rank'), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('applies_with', sa.String(length=50), nullable=True),
    sa.Column('partnerApplicationId', sa.Integer(), nullable=True),
    sa.Column('preferredRoom', sa.String(length=50), nullable=True),
    sa.Column('seatRollover', sa.Boolean(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partnerApplicationId'], ['application.application_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('seats')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('application_season')
    # ### end Alembic commands ###
