"""empty message

Revision ID: 9eea19c03d62
Revises: 7f7b863179cb
Create Date: 2019-03-05 19:24:22.320207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eea19c03d62'
down_revision = '7f7b863179cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('preferredRoom', sa.String(length=50), nullable=True))
    op.add_column('application', sa.Column('seatRollover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'seatRollover')
    op.drop_column('application', 'preferredRoom')
    # ### end Alembic commands ###
