"""empty message

Revision ID: b30d0f2e08fe
Revises: 
Create Date: 2019-02-26 18:19:37.588882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30d0f2e08fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_season',
    sa.Column('application_season_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=False),
    sa.Column('applicationperiodstart', sa.DateTime(), nullable=True),
    sa.Column('applicationperiodend', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_season_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seats',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.String(length=2), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('room_id', 'seat_id'),
    sa.UniqueConstraint('room_id', 'seat_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('needs', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('applies_with', sa.String(length=50), nullable=True),
    sa.Column('partnerApplicationId', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partnerApplicationId'], ['application.application_id'], ),
    sa.ForeignKeyConstraint(['room_id', 'seat_id'], ['seats.room_id', 'seats.seat_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('seats')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('application_season')
    # ### end Alembic commands ###
