"""empty message

Revision ID: bd686c367b77
Revises: 4e32ad44e163
Create Date: 2019-02-06 09:58:31.402418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd686c367b77'
down_revision = '4e32ad44e163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('applies_with', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'applies_with')
    # ### end Alembic commands ###
