"""empty message

Revision ID: d78c6ce642e9
Revises: 9012968eb74d
Create Date: 2019-03-19 14:31:48.336292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78c6ce642e9'
down_revision = '9012968eb74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seats', ['room_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    # ### end Alembic commands ###
