"""empty message

Revision ID: dbc7991281d4
Revises: 91d6388a4976
Create Date: 2019-03-30 14:19:23.229947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc7991281d4'
down_revision = '91d6388a4976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seats_room_id_seat_name_key', 'seats', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('seats_room_id_seat_name_key', 'seats', ['room_id', 'seat_name'])
    # ### end Alembic commands ###
