"""empty message

Revision ID: ec50f46fd247
Revises: bd686c367b77
Create Date: 2019-02-06 13:14:08.025643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50f46fd247'
down_revision = 'bd686c367b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('partnerApplicationId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'application', 'application', ['partnerApplicationId'], ['application_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'partnerApplicationId')
    # ### end Alembic commands ###
