"""empty message

Revision ID: f23193dc3876
Revises: f400ac2e819f
Create Date: 2019-01-29 14:38:01.370732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23193dc3876'
down_revision = 'f400ac2e819f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_season',
    sa.Column('application_season_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=False),
    sa.Column('acceptstart', sa.DateTime(), nullable=True),
    sa.Column('acceptend', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_season_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_season')
    # ### end Alembic commands ###
