export const _SEASON_TITLE = 'Application Seasons';
export const _LINK_STATUS = 'Status';
export const _LINK_ENDING = 'Ending';
export const _LINK_ENDED = 'Season Has Ended';
export const _LINK_OPEN = 'Season Is Open';
export const _LINK_NOT_OPEN = 'Season Has Not Started';
export const _LINK_OPENING = 'Season Opening';
export const _LINK_SEASON_STARTED = 'Season Started At';
export const _LINK_SEASON_ENDED = 'Season Ended At';
export const _SEASON_NUMBER = (id: number) => `Season #${id}`;
export const _NEW_SEASON = 'Create new application season';
